name: romifleur_server
description: Backend for Romifleur Web (Handling Downloads & Static Serving)
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  http: ^1.1.0
  path: ^1.8.3
  archive: ^3.3.7
  args: ^2.4.2

dev_dependencies:
  lints: ^2.1.1
